blank_issues_enabled: false
contact_links:
  - name: Ory Kratos SelfService UI Node Example Forum
    url: https://github.com/ory/kratos-selfservice-ui-node/discussions
    about:
      Please ask and answer questions here, show your implementations and
      discuss ideas.
  - name: Ory Chat
    url: https://www.ory.sh/chat
    about:
      Hang out with other Ory community members to ask and answer questions.
