apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: scansure-vault-spc
  namespace: scansure
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.vault.svc.cluster.local:8200"
    roleName: "scansure-role"
    objects: |
      - objectName: "kratos_admin_token"
        secretPath: "secret/data/scansure/kratos/admin"
        objectType: "secret"
        secretKey: "token"
      - objectName: "keto_admin_token"
        secretPath: "secret/scansure/keto/admin"
        objectType: "secret"
        secretKey: "token"
